CREATE DATABASE IF NOT EXISTS school_database CHARACTER SET utf8 COLLATE utf8_spanish_ci;

SHOW CREATE DATABASE school_database;

USE school_database;

CREATE TABLE IF NOT EXISTS STUDENTS (
    student_id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(25) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(30) NOT NULL,
    first_name VARCHAR(25) NOT NULL,
    last_name VARCHAR(25) NOT NULL,
    PRIMARY KEY (student_id)
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_spanish_ci;

DESCRIBE STUDENTS;

ALTER TABLE STUDENTS
    MODIFY COLUMN email VARCHAR(30) NOT NULL UNIQUE;

CREATE TABLE IF NOT EXISTS ROLES (
    role_id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY (role_id)
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_spanish_ci;

CREATE TABLE IF NOT EXISTS STUDENTS_ROLES (
    student_id INT NOT NULL,
    role_id INT NOT NULL,
    CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES STUDENTS(student_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES ROLES(role_id) ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_spanish_ci;

SHOW INDEX FROM ROLES;

ALTER TABLE ROLES
    DROP INDEX name;

SELECT * FROM STUDENTS;
SELECT * FROM ROLES;
SELECT * FROM STUDENTS_ROLES;